version: "3"
services:

  database:
    
    image: mysql:5.6
    container_name: database
    restart: always
    networks:
      - wpnet
    volumes:
      - mysql-vol:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  
  wordpress:
        
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    depends_on:
      - database        
    restart: always
    networks:
      - wpnet
    volumes:
      - wordpress-vol:/var/www/html/
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress 
      - WORDPRESS_DB_NAME=wordpress

  nginx:    

    image: nginx:alpine
    container_name: nginx
    depends_on:
      - wordpress 
    restart: always
    networks:
      - wpnet
    volumes:
      - wordpress-vol:/var/www/html/    
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.crt:/etc/ssl/certs/ssl.crt
      - ./ssl.key:/etc/ssl/private/ssl.key
    ports:
      - "80:80"
      - "443:443"  

volumes:
  wordpress-vol:
  mysql-vol:
    
networks:
  wpnet:
